package de.zbs.nationz.jobs.architect;

public enum RegionAction {
	
	BREAK_BLOCK,
	PLACE_BLOCK,
	OPEN_CHESTS,
	USE_DOORS,
	USE_BUTTONS,
	USE_NONINVENTORY_BLOCKS,
	USE_INVENTORY_BLOCKS,
	USE_PLATES,
	DAMAGE_MONSTERS,
	DAMAGE_ANIMALS,
	DAMAGE_PLAYERS,
	RIDE_ANIMALS,
	SLEEP,
	IGNITE_TNT,
	VEHICLE_PLACE,
	VEHICLE_DESTROY,
	ITEMFRAME_USE,
	FLINT_N_STEEL
	
}